name: fontApp_main_202.dart
description: 폰트 추가하기
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  use-material-design: true
  
  # 폰트를 추가하는 코드
  fonts:
    - faily : nanum
      fonts:
        - asset: font/NanumPen.ttf
          weight: 500
